server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation # 聚合模式：使用gateway/application-aggregation.yaml中的配置
    # active: dev  # 微服务模式：使用gateway/application-dev.yaml中的配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: common-nacos-dev.magestack.cn:8848
